write.csv(data_test, 'data_test.csv', row.names = F)


library(stringdist)
library(stringr)


modified_jaccard <- function (a, b, q=2){
  #this is the modified jaccard value, it will compute the proportion of how many qgrams in common 
  #to the qgrams generated by a
  #
  l_a <- qgrams(tolower(a), q=q)
  # print(l_a)
  l_b <- qgrams(tolower(b), q=q)
  # print(l_b)
  qgram_a <- dimnames(l_a)[[2]]
  qgram_b <- dimnames(l_b)[[2]]
  total <- sum(l_a)
  common <- 0
  for (i in 1:length(qgram_b)){
    x <- which(qgram_a == qgram_b[i])
    if (!is.integer0(x)){
      # print(qgram_b[i])
      # print(qgram_a[x])
      # print(min(l_b[i], l_a[x]))
      common <- common + min(l_b[i], l_a[x])
    }
  }
  return(common/total)
}

jaccard_test2 <- function(x, match_model, q, threshold = 0.8){
  x <- sub('-', '', x)
  x <- sub(' ', '', x)
  score <- sapply(match_model, modified_jaccard, b = x, q=q)
  # print(score)
  indexes <- which(score >= threshold)
  # print(indexes)
  if (length(indexes) > 1){
    max_length <- max(sapply(indexes, function(x) str_length(match_model[x])))
    indexes <- subset(indexes, sapply(indexes, function(x) str_length(match_model[x]) == max_length))
    # print(indexes)
  }
  return(indexes)
}


# merge the fars data and the existing merged dat

library(readstata13)
fars <- read.dta13('Merge/accidents_quarterly_apr24.dta')
data_test = read.csv("data_test.csv")

# change september to 9
fars$model_word[fars$model_word == '5-Sep'] <- '9-5'

uniquemodels <- unique(fars[,1:2])
uniquemodels$make_word[! tolower(uniquemodels$make_word) %in% data_test$BrandName]

# change wrx to impreza
data_test$ModelName[data_test$TestName == 'wrx'] <- 'impreza'


# find the accurate match for unique models
strippedmodel <- gsub('-','',uniquemodels$model_word)
strippedmodel <- gsub(' ','',strippedmodel)
strippedmodel <- tolower(strippedmodel)

find_index <- function(name, brand){
  index <- which(data_test$TestName == name)
  index <- index[data_test$BrandName[index] == brand]
  return(index)
}

indexes <- mapply(find_index, name =strippedmodel,brand = gsub('-','',tolower(uniquemodels$make_word)))
data_test$BrandName <- as.character(data_test$BrandName)

names <- as.character(lapply(indexes, function(x) data_test$ModelName[x]))
brands <- as.character(lapply(indexes, function(x) data_test$BrandName[x]))

uniquemodels$MatchedModelName <- ifelse(names == "character(0)", NA, names)
uniquemodels$MatchedBrandName <- ifelse(brands == "character(0)", NA, brands)

# run modified jaccard test for the rest
indexleft <- is.na(uniquemodels$MatchedModelName)
fars_match <- function(name, brand){
  brand <- tolower(gsub('-','',brand))
  brand <- gsub(' ','',brand)
  matchlist <- data_test[data_test$BrandName == brand,]
  index <- jaccard_test2(name, match_model = matchlist$TestName, q=2, threshold = 0.8)
  if (length(matchlist$ModelName[index]) < 1) return(NA)
  return(c(brand, unique(matchlist$ModelName[index])))
}

#
matchedlist <- mapply(fars_match, name = uniquemodels$model_word[indexleft], brand = uniquemodels$make_word[indexleft])

brands <- lapply(matchedlist, function(x) ifelse(length(x) == 2, x[1], NA))
brands <- as.character(brands)

names <- lapply(matchedlist, function(x) ifelse(length(x) == 2, x[2], NA))
names <- as.character(names)

uniquemodels$MatchedModelName[indexleft] <- names
uniquemodels$MatchedBrandName[indexleft] <- brands

copy <- uniquemodels

# address the things left

uniquemodels$MatchedModelName <- ifelse(uniquemodels$MatchedModelName == 'NA',NA,uniquemodels$MatchedModelName)
uniquemodels$MatchedBrandName <- ifelse(uniquemodels$MatchedBrandName == 'NA',NA,uniquemodels$MatchedBrandName)
uniquemodels$make_word <- ifelse(grepl('other',uniquemodels$make_word, ignore.case = T),uniquemodels$model_word,uniquemodels$make_word)

indexleft <- is.na(uniquemodels$MatchedModelName)
uniquemodels[indexleft,]

# fix the left manually
uniquemodels[uniquemodels$model_word == 'Ram C/V',]$MatchedModelName <- 'rampickup'
uniquemodels[uniquemodels$model_word == 'Ram C/V',]$MatchedBrandName <- 'dodge'

uniquemodels[uniquemodels$model_word == 'F-Series pickup',]$MatchedModelName <- 'fseries'
uniquemodels[uniquemodels$model_word == 'F-Series pickup',]$MatchedBrandName <- 'ford'

uniquemodels[uniquemodels$model_word == 'CLK',]$MatchedModelName <- 'clkclass'
uniquemodels[uniquemodels$model_word == 'CLK',]$MatchedBrandName <- 'mercedesbenz'

uniquemodels[uniquemodels$model_word == 'M/ML Class',]$MatchedModelName <- 'mclass'
uniquemodels[uniquemodels$model_word == 'M/ML Class',]$MatchedBrandName <- 'mercedesbenz'

uniquemodels[uniquemodels$model_word == 'Aztec',]$MatchedModelName <- 'aztek'
uniquemodels[uniquemodels$model_word == 'Aztec',]$MatchedBrandName <- 'pontiac'



notinsafety <- uniquemodels[is.na(uniquemodels$MatchedModelName),1:2]
notinfars <- unique(data_test[!data_test$ModelName %in% uniquemodels$MatchedModelName,c(1:2)])

write.csv(notinsafety,'Merge/notinsafety.csv')
write.csv(notinfars,'Merge/notinfars.csv')

merged_everything <- read.csv('Merge/merged_everything.csv')
model_list <- unique(merged_everything[,2:3])
notinfarsbigmerge <- model_list$ModelName %in% uniquemodels$MatchedModelName
notinfarsbigmerge <- model_list[!notinfarsbigmerge,]
write.csv(notinfarsbigmerge,'Merge/frombigmerge.csv')

###########################################################
# Now editing datasets according to fars

# change some problems
uniquemodels$MatchedModelName[uniquemodels$model_word == 'SLK'] <- 'slkclass'
uniquemodels$MatchedModelName[uniquemodels$model_word == 'Tesla'] <- 'models'
uniquemodels$MatchedBrandName[uniquemodels$model_word == 'Tesla'] <- 'tesla'
uniquemodels$MatchedModelName[uniquemodels$model_word == 'Mini-Cooper'] <- 'cooper'
uniquemodels$MatchedBrandName[uniquemodels$model_word == 'Mini-Cooper'] <- 'mini'
uniquemodels$MatchedModelName[uniquemodels$model_word == 'Pathfinder Armada'] <- 'armada'
uniquemodels$MatchedModelName[uniquemodels$model_word == 'LS' & uniquemodels$make_word == 'Saturn' ] <- 'lseries'
uniquemodels$MatchedBrandName[uniquemodels$model_word == 'LS' & uniquemodels$make_word == 'Saturn' ] <- 'saturn'


# merge some models 

# fars
uniquemodelscopy <- uniquemodels
uniquemodels$MatchedModelName[uniquemodels$model_word == 'Cherokee/Grand Cherokee'] <- 'cherokee/grandcherokee'
uniquemodels$MatchedModelName[uniquemodels$model_word == 'Accord'] <- 'accord/crosstour'
uniquemodels$MatchedModelName[uniquemodels$MatchedModelName == 'grandmarquis'] <- 'marquis/grandmarquis/monterey'
uniquemodels$MatchedModelName[uniquemodels$model_word == 'Trans Sport/Montana/SV6'] <- 'montana/montanasv6'
uniquemodels$MatchedModelName[uniquemodels$model_word == 'RL/RLX'] <- 'rl/rlx'
uniquemodels$MatchedModelName[uniquemodels$MatchedModelName == 'elr'] <- 'ct6'
uniquemodels$MatchedModelName[uniquemodels$model_word == 'Fullsize Blazer/Tahoe'] <- 'fullsizeblazer/tahoe'
uniquemodels$MatchedModelName[uniquemodels$model_word == 'Genesis'] <- 'genesis/g90'
uniquemodels$MatchedModelName[uniquemodels$MatchedModelName == 'a4/s4/rs4' | uniquemodels$MatchedModelName == 'a6/s6'] <- 'a4/s4/rs4/a6/s6'
uniquemodels$MatchedModelName[uniquemodels$model_word == 'S4/S6'] <- 'a4/s4/rs4/a6/s6'
uniquemodels$MatchedBrandName[uniquemodels$model_word == 'S4/S6'] <- 'audi'
uniquemodels$MatchedModelName[uniquemodels$model_word == '350Z/370Z'] <- '350z/370z'
uniquemodels$MatchedBrandName[uniquemodels$model_word == '350Z/370Z'] <- 'nissan'
uniquemodels$MatchedModelName[uniquemodels$MatchedModelName == 'trailblazer'] <- 'blazer/trailblazer'

library(readstata13)
fars <- read.dta13('Merge/accidents_quarterly_apr24.dta')
fars$make_word <- ifelse(grepl('other',fars$make_word, ignore.case = T),fars$model_word,fars$make_word)
fars$model_word[fars$model_word == '5-Sep'] <- '9-5'
fars <- merge(fars, uniquemodels, all = F)
fars <- fars[!is.na(fars$MatchedModelName),]
write.csv(fars, 'fars/fars_merged_models_apr24.csv')


# merge these models for safety
safety_mm <- read.dta13('Merge/safety_ratings.dta')
safety_mm$ModelName[safety_mm$ModelName == 'wrx'] <- 'impreza'

safety_mm$BrandName_N <- safety_mm$BrandName
safety_mm$ModelName_N <- safety_mm$ModelName

safety_mm$ModelName_N[safety_mm$ModelName_N == 'cherokee' | safety_mm$ModelName_N == 'grandcherokee'] <- 'cherokee/grandcherokee'
safety_mm$ModelName_N[safety_mm$ModelName_N == 'accord' | safety_mm$ModelName_N == 'crosstour'] <- 'accord/crosstour'
safety_mm$ModelName_N[safety_mm$ModelName_N == 'grandmarquis' | safety_mm$ModelName_N == 'monterey'] <- 'marquis/grandmarquis/monterey'
safety_mm$ModelName_N[safety_mm$ModelName_N == 'montana' | safety_mm$ModelName_N == 'montanasv6'] <- 'montana/montanasv6'
safety_mm$ModelName_N[safety_mm$ModelName_N == 'rl' | safety_mm$ModelName_N == 'rlx'] <- 'rl/rlx'
safety_mm$ModelName_N[safety_mm$ModelName_N == 'elr'] <- 'ct6'
safety_mm$ModelName_N[safety_mm$ModelName_N == 'tahoe'] <- 'fullsizeblazer/tahoe'
safety_mm$ModelName_N[safety_mm$ModelName_N == 'genesis' | safety_mm$ModelName_N == 'g90'] <- 'genesis/g90'
safety_mm$BrandName_N[safety_mm$ModelName_N == 'genesis' | safety_mm$ModelName_N == 'g90'] <- 'hyundai'
safety_mm$ModelName_N[safety_mm$ModelName_N == 'a4/s4/rs4' | safety_mm$ModelName_N == 'a6/s6'] <- 'a4/s4/rs4/a6/s6'
safety_mm$ModelName_N[safety_mm$ModelName_N == '350z' | safety_mm$ModelName_N == '370z'] <- '350z/370z'
safety_mm$ModelName_N[safety_mm$ModelName_N == 'blazer' | safety_mm$ModelName_N == 'trailblazer'] <- 'blazer/trailblazer'

write.csv(safety_mm, 'fars/safety_merged_models.csv')

#Collapse the safety by weight of the count 
safety_mm$ID <- paste(safety_mm$BrandName_N, safety_mm$ModelName_N, safety_mm$ModelYear, sep='')


weighted_ratings <- lapply(split(safety_mm,safety_mm$ID), function(z){apply(z[,5:96],2,weighted.mean, w=z$count, na.rm=TRUE)})
weighted_ratings <- do.call(rbind, weighted_ratings)
weighted_ratings <- as.data.frame(weighted_ratings)
weighted_ratings$ID <- row.names(weighted_ratings)
safety_mm_weighted <- merge(weighted_ratings, unique(safety_mm[c('BrandName_N','ModelName_N','ModelYear','ID')]))

safety_mm_weighted['count'] <- sapply(safety_mm_weighted$ID, function(x) sum(safety_mm$count[safety_mm$ID == x]))
write.csv(safety_mm_weighted, 'fars/safety_merged_models_weighted.csv')

# merge these models for wards

wards_mm <- read.csv('Wards/Edited_wards_Apr8.csv')
wards_mm$X <- NULL
wards_mm$BrandName_N <- as.character(wards_mm$MatchedBrandName)
wards_mm$ModelName_N <- as.character(wards_mm$MatchedModelName)

# merge the models
wards_mm$ModelName_N[wards_mm$ModelName_N == 'cherokee' | wards_mm$ModelName_N == 'grandcherokee'] <- 'cherokee/grandcherokee'
wards_mm$ModelName_N[wards_mm$ModelName_N == 'accord' | wards_mm$ModelName_N == 'crosstour'] <- 'accord/crosstour'
wards_mm$ModelName_N[wards_mm$ModelName_N == 'grandmarquis' | wards_mm$ModelName_N == 'monterey'] <- 'marquis/grandmarquis/monterey'
wards_mm$ModelName_N[wards_mm$ModelName_N == 'montana' | wards_mm$ModelName_N == 'montanasv6'] <- 'montana/montanasv6'
wards_mm$ModelName_N[wards_mm$ModelName_N == 'rl' | wards_mm$ModelName_N == 'rlx'] <- 'rl/rlx'
wards_mm$ModelName_N[wards_mm$ModelName_N == 'elr'] <- 'ct6'
wards_mm$ModelName_N[wards_mm$ModelName_N == 'tahoe'] <- 'fullsizeblazer/tahoe'
wards_mm$ModelName_N[wards_mm$ModelName_N == 'genesis' | wards_mm$ModelName_N == 'g90'] <- 'genesis/g90'
wards_mm$BrandName_N[wards_mm$ModelName_N == 'genesis' | wards_mm$ModelName_N == 'g90'] <- 'hyundai'
wards_mm$ModelName_N[wards_mm$ModelName_N == 'a4/s4/rs4' | wards_mm$ModelName_N == 'a6/s6'] <- 'a4/s4/rs4/a6/s6'
wards_mm$ModelName_N[wards_mm$ModelName_N == '350z' | wards_mm$ModelName_N == '370z'] <- '350z/370z'
wards_mm$ModelName_N[wards_mm$ModelName_N == 'blazer' | wards_mm$ModelName_N == 'trailblazer'] <- 'blazer/trailblazer'
write.csv(wards_mm, 'fars/wards_merged_models.csv')


#collapse wards
collapsed_wards_mm <- ddply(wards_mm, .(ModelName_N,BrandName_N,ModelYear,TYPE,NEW_BODYSTYLE,NEW_DRIVETYPE), 
                            summarize, med_LENGTHINS = median(LENGTHINS, na.rm = T), med_WIDTHINS = median(WIDTHINS, na.rm = T),
                            med_HEIGHTHINS = median(HEIGHTINS, na.rm = T), med_CC_ = median(CC_, na.rm = T),
                            med_LITER = median(LITER, na.rm = T), med_RETAILPRICE = median(RETAILPRICE, na.rm = T),
                            med_FEDTAXCREDIT = median(FEDTAXCREDIT, na.rm = T),med_NETHPRPM = median(NETHPRPM, na.rm = T),
                            med_TORQUENMRPM = median(TORQUENMRPM, na.rm = T), med_WEIGHTLBS = median(WEIGHTLBS, na.rm = T),
                            med_EPAMPGECITY = median(EPAMPGECITY, na.rm = T), med_EPAMPGEHW = median(EPAMPGEHW, na.rm = T), 
                            med_EPA_COMBINED = median(EPA_COMBINED, na.rm = T), med_temp = median(temp, na.rm = T), 
                            med_temp = median(temp, na.rm = T)
)
duplicates <- collapsed_wards_mm[duplicated(collapsed_wards_mm[,c(1,2,3)]) | duplicated(collapsed_wards_mm[,c(1,2,3)], fromLast = T),]
models_with_duplicates <- merge(duplicates, wards_mm, all.x = T, by=names(duplicates)[1:6])
models_with_duplicates <- models_with_duplicates[,c(c(1:6),c(21:23))]
models_with_duplicates <- models_with_duplicates[!is.na(models_with_duplicates$ModelName_N),]

# fix some discrepancies within wards data

# combine AWD and non-AWD to non-AWD of a4/s4/rs4/a6/s6
wards_mm <- read.csv('fars/wards_merged_models.csv')
wards_mm$X <- NULL
temp <- models_with_duplicates[models_with_duplicates$ModelName_N=='a4/s4/rs4/a6/s6' & models_with_duplicates$NEW_DRIVETYPE == 'AWD',]
for (i in 1:length(temp[,1])){
  wards_mm[wards_mm$ModelGeneral == temp[i,]$ModelGeneral
           & wards_mm$ModelYear == temp[i,]$ModelYear
           & wards_mm$NEW_DRIVETYPE == temp[i,]$NEW_DRIVETYPE,]$NEW_DRIVETYPE <- 'non-AWD'
}


# cross tour cuv to sedan
wards_mm$TYPE[wards_mm$ModelGeneral %in% c('CrosstourEX','CrosstourEX')] <- 'Car'
wards_mm$NEW_BODYSTYLE[wards_mm$ModelGeneral %in% c('CrosstourEX','CrosstourEX')] <- 'sedan'
# ELR change wagon to sedan
wards_mm$NEW_BODYSTYLE[wards_mm$ModelGeneral == 'ELR' & wards_mm$ModelYear == 2016] <- 'sedan'
# Put monterey to sedans
wards_mm$TYPE[wards_mm$ModelGeneral %in% c('MontereyConvenience','Monterey')] <- 'Car'
wards_mm$NEW_BODYSTYLE[wards_mm$ModelGeneral %in% c('MontereyConvenience','Monterey')] <- 'sedan'

# Redo the collapsing
#collapse wards
collapsed_wards_mm <- ddply(wards_mm, .(ModelName_N,BrandName_N,ModelYear,TYPE,NEW_BODYSTYLE,NEW_DRIVETYPE), 
                            summarize, med_LENGTHINS = median(LENGTHINS, na.rm = T), med_WIDTHINS = median(WIDTHINS, na.rm = T),
                            med_HEIGHTHINS = median(HEIGHTINS, na.rm = T), med_CC_ = median(CC_, na.rm = T),
                            med_LITER = median(LITER, na.rm = T), med_RETAILPRICE = median(RETAILPRICE, na.rm = T),
                            med_FEDTAXCREDIT = median(FEDTAXCREDIT, na.rm = T),med_NETHPRPM = median(NETHPRPM, na.rm = T),
                            med_TORQUENMRPM = median(TORQUENMRPM, na.rm = T), med_WEIGHTLBS = median(WEIGHTLBS, na.rm = T),
                            med_EPAMPGECITY = median(EPAMPGECITY, na.rm = T), med_EPAMPGEHW = median(EPAMPGEHW, na.rm = T), 
                            med_EPA_COMBINED = median(EPA_COMBINED, na.rm = T), med_temp = median(temp, na.rm = T), 
                            med_temp = median(temp, na.rm = T)
)
duplicates <- collapsed_wards_mm[duplicated(collapsed_wards_mm[,c(1,2,3)]) | duplicated(collapsed_wards_mm[,c(1,2,3)], fromLast = T),]
models_with_duplicates <- merge(duplicates, wards_mm, all.x = T, by=names(duplicates)[1:6])
models_with_duplicates <- models_with_duplicates[,c(c(1:6),c(21:23))]
models_with_duplicates <- models_with_duplicates[!is.na(models_with_duplicates$ModelName_N),]

write.csv(collapsed_wards_mm, 'fars/wards_merged_models_collapsed.csv')

# load extended unmerged production

production_mm <- read.csv('fars/production_before_merge_EXTENDED_May11.csv')
production_mm$BrandName_N <- as.character(production_mm$MatchedBrandName)
production_mm$ModelName_N <- as.character(production_mm$MatchedModelName)

library(plyr)
# merge the models
production_mm$ModelName_N[production_mm$ModelName_N == 'cherokee' | production_mm$ModelName_N == 'grandcherokee'] <- 'cherokee/grandcherokee'
production_mm$ModelName_N[production_mm$ModelName_N == 'accord' | production_mm$ModelName_N == 'crosstour'] <- 'accord/crosstour'
production_mm$ModelName_N[production_mm$ModelName_N == 'grandmarquis' | production_mm$ModelName_N == 'monterey'] <- 'marquis/grandmarquis/monterey'
production_mm$ModelName_N[production_mm$ModelName_N == 'montana' | production_mm$ModelName_N == 'montanasv6'] <- 'montana/montanasv6'
production_mm$ModelName_N[production_mm$ModelName_N == 'rl' | production_mm$ModelName_N == 'rlx'] <- 'rl/rlx'
production_mm$ModelName_N[production_mm$ModelName_N == 'elr'] <- 'ct6'
production_mm$ModelName_N[production_mm$ModelName_N == 'tahoe'] <- 'fullsizeblazer/tahoe'
production_mm$ModelName_N[production_mm$ModelName_N == 'genesis' | production_mm$ModelName_N == 'g90'] <- 'genesis/g90'
production_mm$BrandName_N[production_mm$ModelName_N == 'genesis' | production_mm$ModelName_N == 'g90'] <- 'hyundai'
production_mm$ModelName_N[production_mm$ModelName_N == 'a4/s4/rs4' | production_mm$ModelName_N == 'a6/s6'] <- 'a4/s4/rs4/a6/s6'
production_mm$ModelName_N[production_mm$ModelName_N == '350z' | production_mm$ModelName_N == '370z'] <- '350z/370z'
production_mm$ModelName_N[production_mm$ModelName_N == 'blazer' | production_mm$ModelName_N == 'trailblazer'] <- 'blazer/trailblazer'

quarter <- production_mm$ReportingDateQuarterly
quotient <- (quarter - 176)%/%4
remainder <- (quarter - 176) %% 4

ReportingDateQuarterly <- paste(2004+quotient, 'q',remainder + 1, sep = "")
production_mm$NewReportingDateQuarterly <- ReportingDateQuarterly

production_mm <- ddply(production_mm,.(ModelName_N,BrandName_N,MODEL_YEAR,ReportingDateQuarterly,NewReportingDateQuarterly),summarize,SumCumulativeProd = sum(CumulativeProduction))
write.csv(production_mm, 'fars/production_merged_models_May11.csv')


# merge wards and safety
safety_mm_weighted <- read.csv('fars/safety_merged_models_weighted.csv')
collapsed_wards_mm <- read.csv('fars/wards_merged_models_collapsed.csv')

safety_mm_weighted$X <- NULL
collapsed_wards_mm$X <- NULL

collapsed_wards_mm <- collapsed_wards_mm[collapsed_wards_mm$ModelYear < 2018,]
safety_mm_weighted <- safety_mm_weighted[safety_mm_weighted$ModelYear < 2018,]

# drop the NA's
merged_table_mm <- merge(safety_mm_weighted, collapsed_wards_mm, all.x = T)

production_mm <- read.csv( 'fars/production_merged_models_May11.csv')
production_mm$X <- NULL
production_mm$ModelYear <- production_mm$MODEL_YEAR
production_mm$MODEL_YEAR <- NULL

merged_table_mm$ID <- NULL
merged_table_mm.3 <- merge(merged_table_mm, production_mm, all = F)
merged_table_mm.3 <- merged_table_mm.3[merged_table_mm.3$ReportingDateQuarterly >=180,]

write.csv(merged_table_mm.3, 'fars/3waymerged_withmm_May11.csv',row.names = F)

# collapse fars and merge with fars
fars_mm <- read.csv('fars/fars_merged_models_apr24.csv')
fars_mm$X <- NULL
fars_mm$NewReportingDateQuarterly <- paste(fars_mm$year,'q',fars_mm$quarter,sep='')

fars_mm$ModelName_N <- fars_mm$MatchedModelName
fars_mm$BrandName_N <- fars_mm$MatchedBrandName
fars_mm$MatchedBrandName <- NULL
fars_mm$MatchedModelName <- NULL
fars_mm$ModelName <- NULL
fars_mm$model_word <- NULL
fars_mm$BrandName <- NULL
fars_mm$make_word <- NULL
fars_mm$year <- NULL
fars_mm$quarter <-NULL

fars_mm$ID <- paste(fars_mm$BrandName_N, fars_mm$ModelName_N, fars_mm$ModelYear, fars_mm$NewReportingDateQuarterly,sep='')

# weighted_characteristics <- lapply(split(fars_mm,fars_mm$ID), function(z){apply(z[,5:48],2,weighted.mean, w=z$accidents, na.rm=TRUE)})
# weighted_characteristics <- do.call(rbind, weighted_characteristics)
# weighted_characteristics <- as.data.frame(weighted_characteristics)
# weighted_characteristics$ID <- row.names(weighted_characteristics)

sum_accidents <- lapply(split(fars_mm,fars_mm$ID), function(z){apply(z[,2:52],2,sum, na.rm=TRUE)})
sum_accidents <- do.call(rbind, sum_accidents)
sum_accidents <- as.data.frame(sum_accidents)
sum_accidents$ID <- row.names(sum_accidents)

fars_mm_sumed <- merge(sum_accidents, unique(fars_mm[c('BrandName_N','ModelName_N','ModelYear','ID','NewReportingDateQuarterly')]))
fars_mm_sumed <- merge(fars_mm_sumed, sum_accidents)

write.csv(fars_mm_sumed, 'fars/fars_summed_Apr24.csv', row.names = F)


# merge with fars
fars_mm_sumed <- read.csv('fars/fars_summed_Apr24.csv')
merged_table_mm.3 <- read.csv( 'fars/3waymerged_withmm.csv')
merged_table_mm.4 <- merge(merged_table_mm.3, fars_mm_sumed, all.x = T)

# set all accident variable with production > 0 to 0
for (i in 118:168){
  print(names(merged_table_mm.4)[i])
  merged_table_mm.4[,i] <- ifelse(is.na(merged_table_mm.4[,i]) & merged_table_mm.4$SumCumulativeProd >0, 0, merged_table_mm.4[,i])
                                  
}


write.csv(merged_table_mm.4, 'fars/4waymerged_withmm_May_9.csv',row.names = F)

### New Datasets May 10

library(readstata13)
cond_death <- read.dta13('Merge/cond_deaths_may9.dta')
farsmay9 <- read.dta13('Merge/accidents_quarterly_may9.dta')

write.csv(data_test, file='intermediary_data/data_test.csv', row.names = F)
######################### merge fars functions #####################################
# this method preprocess the fars data frame to a data set with matched brand name 
# and model name, without collapsing
preprocess_fars <- function(data){
  data$make_word <- as.character(data$make_word)
  data$model_word <- as.character(data$model_word)
  library(stringdist)
  library(stringr)
  data_test <- read.csv('intermediary_data/data_test.csv')
  for (name in names(data_test)){
    data_test[name] <- as.character(as.vector(data_test[[name]]))
  }
  # change september to 9
  print('preprocess fars.....')
  data$model_word[data$model_word == '5-Sep'] <- '9-5'
  
  uniquemodels <- unique(data[c('make_word','model_word')])
  uniquemodels$make_word[! tolower(uniquemodels$make_word) %in% data_test$BrandName]
  
  # change wrx to impreza
  data_test$ModelName[data_test$TestName == 'wrx'] <- 'impreza'
  
  # find the accurate match for unique models
  strippedmodel <- gsub('-','',uniquemodels$model_word)
  strippedmodel <- gsub(' ','',strippedmodel)
  strippedmodel <- tolower(strippedmodel)
  
  find_index <- function(name, brand){
    index <- which(data_test$TestName == name)
    index <- index[data_test$BrandName[index] == brand]
    return(index)
  }
  
  indexes <- mapply(find_index, name =strippedmodel,brand = gsub('-','',tolower(uniquemodels$make_word)))
  data_test$BrandName <- as.character(data_test$BrandName)
  
  names <- as.character(lapply(indexes, function(x) data_test$ModelName[x]))
  brands <- as.character(lapply(indexes, function(x) data_test$BrandName[x]))
  
  uniquemodels$MatchedModelName <- ifelse(names == "character(0)", NA, names)
  uniquemodels$MatchedBrandName <- ifelse(brands == "character(0)", NA, brands)
  
  # run modified jaccard test for the rest
  indexleft <- is.na(uniquemodels$MatchedModelName)
  fars_match <- function(name, brand){
    brand <- tolower(gsub('-','',brand))
    brand <- gsub(' ','',brand)
    matchlist <- data_test[data_test$BrandName == brand,]
    index <- jaccard_test2(name, match_model = matchlist$TestName, q=2, threshold = 0.8)
    if (length(matchlist$ModelName[index]) < 1) return(NA)
    return(c(brand, unique(matchlist$ModelName[index])))
  }
  
  #
  matchedlist <- mapply(fars_match, name = uniquemodels$model_word[indexleft], brand = uniquemodels$make_word[indexleft])
  
  brands <- lapply(matchedlist, function(x) ifelse(length(x) == 2, x[1], NA))
  brands <- as.character(brands)
  
  names <- lapply(matchedlist, function(x) ifelse(length(x) == 2, x[2], NA))
  names <- as.character(names)
  
  uniquemodels$MatchedModelName[indexleft] <- names
  uniquemodels$MatchedBrandName[indexleft] <- brands
  
  copy <- uniquemodels
  
  # address the things left
  
  uniquemodels$MatchedModelName <- ifelse(uniquemodels$MatchedModelName == 'NA',NA,uniquemodels$MatchedModelName)
  uniquemodels$MatchedBrandName <- ifelse(uniquemodels$MatchedBrandName == 'NA',NA,uniquemodels$MatchedBrandName)
  uniquemodels$make_word <- ifelse(grepl('other',uniquemodels$make_word, ignore.case = T),uniquemodels$model_word,uniquemodels$make_word)
  
  indexleft <- is.na(uniquemodels$MatchedModelName)
  uniquemodels[indexleft,]
  
  # fix the left manually
  uniquemodels[uniquemodels$model_word == 'Ram C/V',]$MatchedModelName <- 'rampickup'
  uniquemodels[uniquemodels$model_word == 'Ram C/V',]$MatchedBrandName <- 'dodge'
  
  uniquemodels[uniquemodels$model_word == 'F-Series pickup',]$MatchedModelName <- 'fseries'
  uniquemodels[uniquemodels$model_word == 'F-Series pickup',]$MatchedBrandName <- 'ford'
  
  uniquemodels[uniquemodels$model_word == 'CLK',]$MatchedModelName <- 'clkclass'
  uniquemodels[uniquemodels$model_word == 'CLK',]$MatchedBrandName <- 'mercedesbenz'
  
  uniquemodels[uniquemodels$model_word == 'M/ML Class',]$MatchedModelName <- 'mclass'
  uniquemodels[uniquemodels$model_word == 'M/ML Class',]$MatchedBrandName <- 'mercedesbenz'
  
  uniquemodels[uniquemodels$model_word == 'Aztec',]$MatchedModelName <- 'aztek'
  uniquemodels[uniquemodels$model_word == 'Aztec',]$MatchedBrandName <- 'pontiac'
  
  
  ###########################################################
  # Now editing datasets according to fars
  
  # change some problems
  uniquemodels$MatchedModelName[uniquemodels$model_word == 'SLK'] <- 'slkclass'
  uniquemodels$MatchedModelName[uniquemodels$model_word == 'Tesla'] <- 'models'
  uniquemodels$MatchedBrandName[uniquemodels$model_word == 'Tesla'] <- 'tesla'
  uniquemodels$MatchedModelName[uniquemodels$model_word == 'Mini-Cooper'] <- 'cooper'
  uniquemodels$MatchedBrandName[uniquemodels$model_word == 'Mini-Cooper'] <- 'mini'
  uniquemodels$MatchedModelName[uniquemodels$model_word == 'Pathfinder Armada'] <- 'armada'
  uniquemodels$MatchedModelName[uniquemodels$model_word == 'LS' & uniquemodels$make_word == 'Saturn' ] <- 'lseries'
  uniquemodels$MatchedBrandName[uniquemodels$model_word == 'LS' & uniquemodels$make_word == 'Saturn' ] <- 'saturn'
  
  
  # merge some models 
  
  # fars
  uniquemodelscopy <- uniquemodels
  uniquemodels$MatchedModelName[uniquemodels$model_word == 'Cherokee/Grand Cherokee'] <- 'cherokee/grandcherokee'
  uniquemodels$MatchedModelName[uniquemodels$model_word == 'Accord'] <- 'accord/crosstour'
  uniquemodels$MatchedModelName[uniquemodels$MatchedModelName == 'grandmarquis'] <- 'marquis/grandmarquis/monterey'
  uniquemodels$MatchedModelName[uniquemodels$model_word == 'Trans Sport/Montana/SV6'] <- 'montana/montanasv6'
  uniquemodels$MatchedModelName[uniquemodels$model_word == 'RL/RLX'] <- 'rl/rlx'
  uniquemodels$MatchedModelName[uniquemodels$MatchedModelName == 'elr'] <- 'ct6'
  uniquemodels$MatchedModelName[uniquemodels$model_word == 'Fullsize Blazer/Tahoe'] <- 'fullsizeblazer/tahoe'
  uniquemodels$MatchedModelName[uniquemodels$model_word == 'Genesis'] <- 'genesis/g90'
  uniquemodels$MatchedModelName[uniquemodels$MatchedModelName == 'a4/s4/rs4' | uniquemodels$MatchedModelName == 'a6/s6'] <- 'a4/s4/rs4/a6/s6'
  uniquemodels$MatchedModelName[uniquemodels$model_word == 'S4/S6'] <- 'a4/s4/rs4/a6/s6'
  uniquemodels$MatchedBrandName[uniquemodels$model_word == 'S4/S6'] <- 'audi'
  uniquemodels$MatchedModelName[uniquemodels$model_word == '350Z/370Z'] <- '350z/370z'
  uniquemodels$MatchedBrandName[uniquemodels$model_word == '350Z/370Z'] <- 'nissan'
  uniquemodels$MatchedModelName[uniquemodels$MatchedModelName == 'trailblazer'] <- 'blazer/trailblazer'
  
  data$make_word <- ifelse(grepl('other',data$make_word, ignore.case = T),data$model_word,data$make_word)
  data$model_word[data$model_word == '5-Sep'] <- '9-5'
  data <- merge(data, uniquemodels, all = F)
  data <- data[!is.na(data$MatchedModelName),]
  print('preprocess complete')
  return(data)
}

sum_fars <- function(fars_mm, len_newvar){
  print('collapsing(sum) fars.....')
  
  fars_mm$NewReportingDateQuarterly <- paste(fars_mm$year,'q',fars_mm$quarter,sep='')
  
  fars_mm$ModelName_N <- fars_mm$MatchedModelName
  fars_mm$BrandName_N <- fars_mm$MatchedBrandName
  fars_mm$MatchedBrandName <- NULL
  fars_mm$MatchedModelName <- NULL
  fars_mm$ModelName <- NULL
  fars_mm$model_word <- NULL
  fars_mm$BrandName <- NULL
  fars_mm$make_word <- NULL
  fars_mm$year <- NULL
  fars_mm$quarter <-NULL
  
  fars_mm$ID <- paste(fars_mm$BrandName_N, fars_mm$ModelName_N, fars_mm$ModelYear, fars_mm$NewReportingDateQuarterly,sep='')
  
  # weighted_characteristics <- lapply(split(fars_mm,fars_mm$ID), function(z){apply(z[,5:48],2,weighted.mean, w=z$accidents, na.rm=TRUE)})
  # weighted_characteristics <- do.call(rbind, weighted_characteristics)
  # weighted_characteristics <- as.data.frame(weighted_characteristics)
  # weighted_characteristics$ID <- row.names(weighted_characteristics)
  
  # The indexing here need to adjust every time !!!!
  start = which(names(fars_mm) == 'accidents')
  end = start + len_newvar - 1
  print(paste('from: ',names(fars_mm)[start]))
  print(paste('to: ',names(fars_mm)[end]))
  sum_accidents <- lapply(split(fars_mm,fars_mm$ID), function(z){apply(z[,start:end],2,sum, na.rm=TRUE)})
  sum_accidents <- do.call(rbind, sum_accidents)
  sum_accidents <- as.data.frame(sum_accidents)
  sum_accidents$ID <- row.names(sum_accidents)
  
  fars_mm_sumed <- merge(sum_accidents, unique(fars_mm[c('BrandName_N','ModelName_N','ModelYear','ID','NewReportingDateQuarterly')]))
  fars_mm_sumed <- merge(fars_mm_sumed, sum_accidents)
  print('collapsing complete')
  
  return(fars_mm_sumed)
}

# call this method to merge fars and 3 way merged file
merge_fars <- function(threewaymerge, fars, len_newvar){
  fars_mm <- preprocess_fars(fars)
  fars_mm_sumed <- sum_fars(fars_mm, len_newvar)
  print('merging.....')
  merged_table_mm.4 <- merge(threewaymerge, fars_mm_sumed, all.x = T)
  return(merged_table_mm.4)
}




##########################################################################################
# Creating 4 way merge here
library(readstata13)
fars <- read.dta13('fars/accidents_quarterly_may23.dta')
print(names(fars)[which(names(fars) == 'ModelName') - 1])
len_newvar = which(names(fars) == 'ModelName') - which(names(fars) == 'accidents')
merged_table_mm.3 <- read.csv( 'fars/3waymerged_withmm_May11.csv')
merged_table_mm.4 <- merge_fars(merged_table_mm.3, fars, len_newvar)

# filling the zeros
# set all accident variable with production > 0 to 0
start = which(names(merged_table_mm.4) == 'accidents')
end = start + len_newvar - 1
print(paste('from: ',names(merged_table_mm.4)[start]))
print(paste('to: ',names(merged_table_mm.4)[end]))
for (i in start:end){
  print(names(merged_table_mm.4)[i])
  merged_table_mm.4[,i] <- ifelse(is.na(merged_table_mm.4[,i]) & merged_table_mm.4$SumCumulativeProd >0, 0, merged_table_mm.4[,i])
  
}

write.csv(merged_table_mm.4,'fars/4waymerged_withmm_May_25.csv', row.names = F)


# merge the death condition dataset with the 3 way merged file
cond_death_matched <- preprocess_fars(cond_death)

#creating merging variables

#create quarter
cond_death_matched$quarter <- ifelse(cond_death_matched$month %in% c(1,2,3), 1,
                                     ifelse(cond_death_matched$month %in% c(4,5,6),2,
                                            ifelse(cond_death_matched$month %in% c(7,8,9),3,
                                                   ifelse(cond_death_matched$month %in% c(10,11,12),4,-1))))

cond_death_matched$NewReportingDateQuarterly <- paste(cond_death_matched$year,'q',cond_death_matched$quarter,sep='')

cond_death_matched$ModelName_N <- cond_death_matched$MatchedModelName
cond_death_matched$BrandName_N <- cond_death_matched$MatchedBrandName
cond_death_matched$MatchedBrandName <- NULL
cond_death_matched$MatchedModelName <- NULL
cond_death_matched$ModelName <- NULL
cond_death_matched$model_word <- NULL
cond_death_matched$BrandName <- NULL
cond_death_matched$make_word <- NULL
cond_death_matched$year <- NULL
cond_death_matched$quarter <-NULL

merged_table_mm.3 <- read.csv( 'fars/3waymerged_withmm_May11.csv')
merged_table_mm.cond_death <- merge(merged_table_mm.3, cond_death_matched, all.y = T)
write.csv(merged_table_mm.cond_death, 'fars/4waymerged_conditiondeath.csv', row.names = F)


##### Sep 10, merge cond death with accidents id and accidents count ####
accidents_with_count <- read.csv('Regression/onetwovehacc.csv')
accidents_with_count['X'] <- NULL
accidents_with_count$make_word <- accidents_with_count$Make_Word
accidents_with_count$Make_Word <- NULL
accidents_with_count$model_word <- accidents_with_count$Model_Word
accidents_with_count$Model_Word <- NULL
accidents_with_count_matched <- preprocess_fars(accidents_with_count)

accidents_with_count_matched$NewReportingDateQuarterly <- paste(accidents_with_count_matched$year,'q',accidents_with_count_matched$quarter,sep='')

accidents_with_count_matched$ModelName_N <- accidents_with_count_matched$MatchedModelName
accidents_with_count_matched$BrandName_N <- accidents_with_count_matched$MatchedBrandName
accidents_with_count_matched$MatchedBrandName <- NULL
accidents_with_count_matched$MatchedModelName <- NULL
accidents_with_count_matched$ModelYear <- accidents_with_count_matched$mod_year
accidents_with_count_matched$mod_year <- NULL

merged_table_mm.3 <- read.csv( 'fars/3waymerged_withmm_May11.csv')
merged_table_mm.acc_with_count <- merge(merged_table_mm.3, accidents_with_count_matched, all.y = T)
write.csv(merged_table_mm.acc_with_count, 'fars/4waymerged_acc_with_ve_total.csv', row.names = F)


